### ISSUE TITLE
Implement the lobby class.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#141]

**Comment by paolovic** [comment]
waiting for @apple00juice feedback

**Comment by melihcatal** [comment]
Hi ! 
Could you please reference a commit that closes the issue :) 
Thank you for your effort :)🥇

**Comment by paolovic** [comment]
closed by be965b3d12812c60d0436e968fd2157df2eb21bc
@melihcatal
