### ISSUE TITLE
As a registered user, I want to generate a profile avatar in order to differentiate myself from other users.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#27]
## Acceptance criteria
- [ ] In the user profile, it is possible to add an avatar.
- [ ] The avatar can be chosen from a preselected choice.
- [ ] The avatar is displayed on the lobby when starting a game.

**Comment by apple00juice** [comment]
The product owner deemed that this feature is not necessary, and would diminish the design of the application.
